### ISSUE TITLE
Ear speaker not working during calls / only loudspeaker active

### ISSUE THREAD

**Issue by theraser** [WeAreFairphone/android_device_fairphone_FP3#5]
Thanks for this nearly perfect build, I just bought my FP3 thanks to your work and immediately flashed lineage_16_fp3_20200413. Everything works really smooth, except for the ear speaker. I already noticed your comment about that in the forums, but wanted to discuss this at this more structured place.

Calling somebody will automatically activate the loudspeaker, which cannot be turned off. The microphone is working fine at this point. Additionally it is possible to use a wired headset, this will turn off the loudspeaker just as expected and works without problems.

![Screenshot_20200428-151352_Phone](https://user-images.githubusercontent.com/7988080/80491450-0365eb00-8963-11ea-9931-d734b5e790f0.png)

**Comment by dk1978** [comment]
Hi @theraser,
thank you for your confidence in us!
I assume you pulled the ROM from [https://androidhost.org/T2RSWvp](here)? Since it dates from 2020-04-13 I will just assume this is already fixed in the repository now. Maybe Max can upload a new image very soon - or you can try building the image yourself as described on the [README](https://github.com/WeAreFairphone/android_device_fairphone_FP3).

**Comment by theraser** [comment]
Ah, thanks a lot! Now I also see the commit 8f5c0d1f48f1ccce34a56ed250cd75d879b81a39, which should do the job. Maybe I will find some time to setup a build system, there is no one at the moment. If there is a new image available I will be happy to report back here.

**Comment by mstaz** [comment]
Yes, I think i didn't upload images for that. Unfortunately I don't have time to do it today.

**Comment by theraser** [comment]
I just tested my first own build and the error is gone as expected. Thanks for your help!
